export const projects = [
  {
    id: "1",
    title: "Pixelated Chilies",
    description: "A brief description of project one.",
    imageUrl: "/assets/pixelated-chilies.svg",
    link: "https://pxchilies.com",
  },
  {
    id: "2",
    title: "Zeropozitive",
    description: "A brief description of project two.",
    imageUrl: "/assets/zeropozitive.svg",
    link: "https://zeropozitive.com",
  },
  {
    id: "3",
    title: "Triosalon",
    description: "A brief description of project two.",
    imageUrl: "/assets/trio-salon.svg",
    link: "https://triosalon.net",
  },
  {
    id: "4",
    title: "Pi Relations",
    description: "A brief description of project two.",
    imageUrl: "/assets/pi-relations.svg",
    link: "https://pirelations.com",
  },
  {
    id: "5",
    title: "Possibilities for Partners",
    description: "A brief description of project two.",
    imageUrl: "/assets/pfp-ks.svg",
    link: "https://pfp-ks.com",
  },
  {
    id: "6",
    title: "Aesthetic Supply",
    description: "A brief description of project two.",
    imageUrl: "/assets/aesthetic-supply.svg",
    link: "https://aesthetic-supply.ch",
  },
  {
    id: "7",
    title: "Sportsmed",
    description: "A brief description of project two.",
    imageUrl: "/assets/sports-med.svg",
    link: "https://sports-med.ch",
  },
  {
    id: "8",
    title: "Zeropozitive Estate",
    description: "A brief description of project two.",
    imageUrl: "/assets/zeropozitive.estate.svg",
    link: "https://zeropozitive.estate",
  },
  {
    id: "9",
    title: "Pika Group",
    description: "A brief description of project two.",
    imageUrl: "/assets/arc-construction.svg",
    link: "https://pikagroupks.com",
  },
  {
    id: "10",
    title: "Albasky",
    description: "A brief description of project two.",
    imageUrl: "/assets/albasky.svg",
    link: "https://albasky.online",
  },
  {
    id: "11",
    title: "Flori Diamonds",
    description: "A brief description of project two.",
    imageUrl: "/assets/flori-diamonds.svg",
    link: "https://flori.diamonds",
  },
  {
    id: "12",
    title: "Mashtra",
    description: "A brief description of project two.",
    imageUrl: "/assets/mashtra.svg",
    link: "https://mashtra.com",
  },
];
