export const projects = [
  {
    id: "1",
    title: "Pixelated Chilies",
    description: "A brief description of project one.",
    imageUrl: "/assets/pixelated-chilies.svg",
    link: "https://pxchilies.com",
  },
  {
    id: "2",
    title: "Zeropozitive",
    description: "A brief description of project two.",
    imageUrl: "/assets/zeropozitive.svg",
    link: "https://zeropozitive.com",
  },
  {
    id: "3",
    title: "Triosalon",
    description: "A brief description of project two.",
    imageUrl: "/assets/trio-salon.svg",
    link: "https://triosalon.net",
  },
  {
    id: "4",
    title: "Pi Relations",
    description: "A brief description of project two.",
    // imageUrl: "https://via.placeholder.com/300",
    link: "",
  },
  {
    id: "5",
    title: "Possibilities for Partners",
    description: "A brief description of project two.",
    // imageUrl: "https://via.placeholder.com/300",
    link: "",
  },
  {
    id: "6",
    title: "Aesthetic Supply",
    description: "A brief description of project two.",
    // imageUrl: "https://via.placeholder.com/300",
    link: "",
  },
  {
    id: "7",
    title: "Sportsmed",
    description: "A brief description of project two.",
    // imageUrl: "https://via.placeholder.com/300",
    link: "",
  },
  {
    id: "8",
    title: "Zeropozitive Estate",
    description: "A brief description of project two.",
    // imageUrl: "https://via.placeholder.com/300",
    link: "",
  },
  {
    id: "9",
    title: "Pika Group",
    description: "A brief description of project two.",
    // imageUrl: "https://via.placeholder.com/300",
    link: "",
  },
  {
    id: "10",
    title: "Albasky",
    description: "A brief description of project two.",
    // imageUrl: "https://via.placeholder.com/300",
    link: "",
  },
  {
    id: "11",
    title: "Fanaj Transport",
    description: "A brief description of project two.",
    // imageUrl: "https://via.placeholder.com/300",
    link: "",
  },
  {
    id: "12",
    title: "Mashtra",
    description: "A brief description of project two.",
    // imageUrl: "https://via.placeholder.com/300",
    link: "",
  },
];
